name: Daily Page Change Check - Push Notification

on:
  schedule:
    - cron: "0 * * * *"  # This cron expression means every hour at the top of the hour
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest  # Specifies the environment to run on (Ubuntu in this case)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out your repository to the runner

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # You can change the Python version as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 # Install the required libraries, e.g., requests, beautifulsoup4

      - name: Run page change detection script
        run: python main.py  # Replace with the actual path to your script

      - name: Send push notification on failure
        if: failure()
        uses: techulus/push-github-action@1.0.0
        env:
          API_KEY: ${{ secrets.API_KEY_TECHULUS }}
          MESSAGE: "There is a new ticket on Treasure Cup"
