name: Daily Page Change Check

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest  # Specifies the environment to run on (Ubuntu in this case)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out your repository to the runner

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # You can change the Python version as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 # Install the required libraries, e.g., requests, beautifulsoup4

      - name: Run page change detection script
        run: python main.py  # Replace with the actual path to your script

      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: smtp.gmail.com  # Replace with your email server
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Treasure CUP page has change"
          body: "reasure CUP page has change check this link https://www.ccgeventos.com.br/informa-es-do-evento-e-registro/treasure-cup-one-piece-card-game"
          to: marciohariki@gmail.com  # Replace with recipient's email
          from: marciohariki@gmail.com  # Replace with sender's email