name: Daily Page Change Check

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest  # Specifies the environment to run on (Ubuntu in this case)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out your repository to the runner

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # You can change the Python version as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests  # Install the required libraries, e.g., requests

      - name: Run page change detection script
        run: python main.py  # Replace with the actual path to your script
